---
Name: elemental-decisiontree-output-extension
---
DNADesign\SilverStripeElementalDecisionTree\Model\DecisionTreeAnswer:
  extensions:
    - Silverstripe\Elemental\DecisionTree\Output\DataExtension

DNADesign\SilverStripeElementalDecisionTree\Model\DecisionTreeStep:
  extensions:
    - Silverstripe\Elemental\DecisionTree\Output\DataExtension

DNADesign\SilverStripeElementalDecisionTree\Model\ElementDecisionTree:
  extensions:
    - Silverstripe\Elemental\DecisionTree\Output\BlockExtension

---
Name: elemental-decisiontree-output-cache
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.decisiontree-output:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "output"
